trigger:

  - master

jobs:
  - job: "Linux"
    pool:
      vmImage: "ubuntu-16.04"

    steps:
      - checkout: self
        persistCredentials: true
        clean: true
      - task: NodeTool@0
        inputs:
          versionSpec: "12.x"
        displayName: "Install Node.js"
      - script: |
            ls
      - task: Npm@1
        inputs:
          command: 'install'
          workingDir: '$(Build.SourcesDirectory)'
      - task: Npm@1
        inputs:
          command: 'custom'
          workingDir: '$(Build.SourcesDirectory)'
          customCommand: 'run build'  
      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'Free Trial(4d907b76-52f1-4882-8178-103b9e88c490)'
          appType: 'webAppContainer'
          WebAppName: 'ci-shaw-app'
          DockerNamespace: 'ci:latest'
          DockerRepository: 'shawci.azurecr.io'
          DockerImageTag: 'ci:latest'