trigger:

  - master

jobs:
  - job: "Linux"
    pool:
      vmImage: "ubuntu-16.04"

    steps:
      - checkout: self
        persistCredentials: true
        clean: true
      - task: NodeTool@0
        inputs:
          versionSpec: "12.x"
        displayName: "Install Node.js"
      - script: |
            ls
      - task: Npm@1
        inputs:
          command: 'install'
          workingDir: '$(Build.SourcesDirectory)'
      - task: Npm@1
        inputs:
          command: 'custom'
          workingDir: '$(Build.SourcesDirectory)'
          customCommand: 'run build'
      - task: GitHubComment@0
        inputs:
          gitHubConnection: 'martshaw'
          repositoryName: '$(Build.Repository.Name)'
          comment: 'PR built'

