trigger:
  - master
jobs:
- job: RunTest
  workspace:
    clean: all
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: run christiankm01/master:3.15.5
  - task: Docker@2
    displayName: run
    inputs:
      command: run christiankm01/master:3.15.5
