trigger:

  - master

jobs:
  - job: "Linux"
    pool:
      vmImage: "ubuntu-16.04"

    steps:
      - checkout: self
        persistCredentials: true
        clean: true
      - task: NodeTool@0
        inputs:
          versionSpec: "12.x"
        displayName: "Install Node.js"
      - script: |
            ls
      - task: Npm@1
        inputs:
          command: 'install'
          workingDir: '$(Build.SourcesDirectory)'
        displayName: "Npm Install"
      - task: Npm@1
        inputs:
          command: 'custom'
          workingDir: '$(Build.SourcesDirectory)'
          customCommand: 'run build'
        displayName: "Npm InstalBuildl"
      - task: DockerCompose@0
        inputs:
          containerregistrytype: 'Azure Container Registry'
          azureSubscription: 'Free Trial(4d907b76-52f1-4882-8178-103b9e88c490)'
          azureContainerRegistry: '{"loginServer":"shawci.azurecr.io", "id" : "/subscriptions/4d907b76-52f1-4882-8178-103b9e88c490/resourceGroups/ci/providers/Microsoft.ContainerRegistry/registries/shawci"}'
          dockerComposeFile: '**/docker-compose.yml'
          action: 'Run a Docker Compose command'
          dockerComposeCommand: 'up'
          arguments: '--scale nextjs=3 -d'
        displayName: "Docker Compose"

