version: '3.8'
services:
  app:
    image: martshaw/ci:latest
    expose:
      - "3000"
    deploy:
      mode: replicated
      replicas: 2
  nginx:
    restart: always
    build:
        context: ./nginx
    ports:
        - "80:80"
networks:
  default:
    driver: bridge
    name: app
