apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: nextjs
  name: nextjs
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: nextjs
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: nextjs
    spec:
      containers:
        - image: martshaw/ci:latest
          name: nextjs
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          resources: {}
      restartPolicy: Always
status: {}
